sources:
  - name: thelook_ecommerce
    database: bigquery-public-data
    tables:
      - name: users

  - name: stg_thelook
    database: data-pipeline-tools
    schema: "{{ target.schema }}_stg_thelook"
    tables:
      - name: users
        description: "Stacked daily Full Refresh from TheLook users data"
        columns:
          - name: id
            data_type: string
          - name: first_name
            data_type: string
          - name: last_name
            data_type: string
          - name: email
            data_type: string
          - name: age
            data_type: string
          - name: gender
            data_type: string
          - name: state
            data_type: string
          - name: street_address
            data_type: string
          - name: postal_code
            data_type: string
          - name: city
            data_type: string
          - name: country
            data_type: string
          - name: latitude
            data_type: string
          - name: longitude
            data_type: string
          - name: traffic_source
            data_type: string
          - name: created_at
            data_type: string
          
        external:
          location: "gs://{{ var('raw_bucket') }}/{{ var('raw_bucket_prefix') }}/full-refresh/users/*.csv"
          options:
            format: CSV
            skip_leading_rows: 1
            hive_partition_uri_prefix: "gs://{{ var('raw_bucket') }}/{{ var('raw_bucket_prefix') }}/full-refresh/users/"
        partitions:
          - name: p_year
            data_type: int
          - name: p_month
            data_type: int
          - name: p_day
            data_type: int
        