sources:
  - name: thelook_ecommerce
    database: bigquery-public-data
    tables:
      - name: users

  - name: stg_thelook
    database: data-pipeline-tools
    schema: "{{ target.schema }}_stg_thelook"
    tables:
      - name: users
        description: "Stacked daily Full Refresh from TheLook users data"
        external:
          location: "gs://{{ var('raw_bucket') }}/{{ var('raw_bucket_prefix') }}/full-refresh/users/*.csv"
          options:
            format: CSV
            skip_leading_rows: 1
            hive_partition_uri_prefix: "gs://{{ var('raw_bucket') }}/{{ var('raw_bucket_prefix') }}/full-refresh/users/"
        partitions:
          - name: p_year
            data_type: int
          - name: p_month
            data_type: int
          - name: p_day
            data_type: int